/*
 * Automatically generated by jrpcgen 1.0.5 on 15.04.03 15:25
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * A collection of constants used by the "demo" ONC/RPC program.
 */
public interface demo {
    public static final int foo_1 = 4;
    public static final int ll_1 = 5;
    public static final int echo_1 = 1;
    public static final int test_2 = 100;
    public static final int checkfoo_2 = 3;
    public static final int checkfoo_1 = 3;
    public static final int C_C = 42;
    public static final int C_A = C_C;
    public static final int C_B = C_A;
    public static final int concat_1 = 2;
    public static final int cat3_2 = 43;
    public static final int FIXEDBUFFERLENGTH = 64;
    public static final int cat_2 = 42;
    public static final int llcat_2 = 55;
    public static final int FIRST_DEMO_VERSION = 1;
    public static final int NULL_2 = 0;
    public static final int NULL_1 = 0;
    public static final int DEMO = 0x20049678;
    public static final int SECOND_DEMO_VERSION = 2;
}
// End of demo.java
