/*
 * Automatically generated by jrpcgen 1.0.5 on 11.11.05 21:24
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
/**
 * A collection of constants used by the "demo2" ONC/RPC program.
 */
public interface demo2 {
    public static final int C_C = 42;
    public static final int C_A = C_C;
    public static final int C_B = C_A;
}
// End of demo2.java
