/*
 * Automatically generated by jrpcgen 1.0.7 on 29.05.07 21:34
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
/**
 * Enumeration (collection of constants).
 */
public interface ENUMFOO2 {

    public static final int FOO = 0;
    public static final int BAR = 0+1;
    public static final int BAZ_1 = demo2.C_B;
    public static final int BAZ_2 = demo2.C_B+1;
    public static final int BAZ_3 = ENUMBAZ2.E_BAZ;

}
// End of ENUMFOO2.java
