/*
 * Automatically generated by jrpcgen 1.0.5 on 15.04.03 15:25
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * Enumeration (collection of constants).
 */
public interface ENUMBAZ {

    public static final int E_BAZ = demo.C_B;

}
// End of ENUMBAZ.java
