/*
 * Automatically generated by jrpcgen 1.0.5 on 14.08.03 10:19
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
/**
 * Enumeration (collection of constants).
 */
public interface ENUMFOO {

    public static final int FOO = 0;
    public static final int BAR = 0+1;
    public static final int BAZ_1 = demo.C_B;
    public static final int BAZ_2 = demo.C_B+1;
    public static final int BAZ_3 = ENUMBAZ.E_BAZ;

}
// End of ENUMFOO.java
