/*
 * Automatically generated by jrpcgen 1.0.7 on 29.05.07 21:34
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
/**
 * Enumeration (collection of constants).
 */
public interface ENUMBAZ {

    public static final int E_BAZ = demo.C_B;

}
// End of ENUMBAZ.java
