/*
 * Automatically generated by jrpcgen 1.0.5 on 11.11.05 21:24
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
/**
 * Enumeration (collection of constants).
 */
public interface ENUMBAZ2 {

    public static final int E_BAZ = demo2.C_B;

}
// End of ENUMBAZ2.java
