/*
 * Automatically generated by jrpcgen 1.0.5 on 15.04.03 15:25
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class LINKEDLIST implements XdrAble {
    public int foo;
    public LINKEDLIST next;

    public LINKEDLIST() {
    }

    public LINKEDLIST(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        LINKEDLIST $this = this;
        do {
            xdr.xdrEncodeInt($this.foo);
            $this = $this.next;
            xdr.xdrEncodeBoolean($this != null);
        } while ( $this != null );
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        LINKEDLIST $this = this;
        LINKEDLIST $next;
        do {
            $this.foo = xdr.xdrDecodeInt();
            $next = xdr.xdrDecodeBoolean() ? new LINKEDLIST() : null;
            $this.next = $next;
            $this = $next;
        } while ( $this != null );
    }

}
// End of LINKEDLIST.java
