/*
 * Automatically generated by jrpcgen 1.0.5 on 11.11.05 21:11
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SILLYSTRUCT implements XdrAble {
    public byte [] fixedbuffer;
    public byte [] buffer;
    public byte [] fixedbytes;
    public byte [] bytes;
    public int ui1;
    public int ui2;
    public String nonsense;

    public SILLYSTRUCT() {
    }

    public SILLYSTRUCT(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeByteFixedVector(fixedbuffer, 512);
        xdr.xdrEncodeByteVector(buffer);
        xdr.xdrEncodeOpaque(fixedbytes, demo.FIXEDBUFFERLENGTH);
        xdr.xdrEncodeDynamicOpaque(bytes);
        xdr.xdrEncodeInt(ui1);
        xdr.xdrEncodeInt(ui2);
        xdr.xdrEncodeString(nonsense);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fixedbuffer = xdr.xdrDecodeByteFixedVector(512);
        buffer = xdr.xdrDecodeByteVector();
        fixedbytes = xdr.xdrDecodeOpaque(demo.FIXEDBUFFERLENGTH);
        bytes = xdr.xdrDecodeDynamicOpaque();
        ui1 = xdr.xdrDecodeInt();
        ui2 = xdr.xdrDecodeInt();
        nonsense = xdr.xdrDecodeString();
    }

}
// End of SILLYSTRUCT.java
