/*
 * Automatically generated by jrpcgen 1.0.7 on 29.05.07 21:34
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SILLYSTRUCT implements XdrAble, java.io.Serializable {
    protected byte [] fixedbuffer;
    protected byte [] buffer;
    protected byte [] fixedbytes;
    protected byte [] bytes;
    protected int ui1;
    protected int ui2;
    protected String nonsense;

    private static final long serialVersionUID = 4109809708757592008L;

    public void setFixedbuffer(byte[] x) { this.fixedbuffer = x; }
    public void setFixedbuffer(int index, byte x) { this.fixedbuffer[index] = x; }
    public byte[] getFixedbuffer() { return this.fixedbuffer; }
    public byte getFixedbuffer(int index) { return this.fixedbuffer[index]; }

    public void setBuffer(byte[] x) { this.buffer = x; }
    public void setBuffer(int index, byte x) { this.buffer[index] = x; }
    public byte[] getBuffer() { return this.buffer; }
    public byte getBuffer(int index) { return this.buffer[index]; }

    public void setFixedbytes(byte[] x) { this.fixedbytes = x; }
    public void setFixedbytes(int index, byte x) { this.fixedbytes[index] = x; }
    public byte[] getFixedbytes() { return this.fixedbytes; }
    public byte getFixedbytes(int index) { return this.fixedbytes[index]; }

    public void setBytes(byte[] x) { this.bytes = x; }
    public void setBytes(int index, byte x) { this.bytes[index] = x; }
    public byte[] getBytes() { return this.bytes; }
    public byte getBytes(int index) { return this.bytes[index]; }

    public void setUi1(int x) { this.ui1 = x; }
    public int getUi1() { return this.ui1; }

    public void setUi2(int x) { this.ui2 = x; }
    public int getUi2() { return this.ui2; }

    public void setNonsense(String x) { this.nonsense = x; }
    public String getNonsense() { return this.nonsense; }

    public SILLYSTRUCT() {
    }

    public SILLYSTRUCT(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeByteFixedVector(fixedbuffer, 512);
        xdr.xdrEncodeByteVector(buffer);
        xdr.xdrEncodeOpaque(fixedbytes, demo.FIXEDBUFFERLENGTH);
        xdr.xdrEncodeDynamicOpaque(bytes);
        xdr.xdrEncodeInt(ui1);
        xdr.xdrEncodeInt(ui2);
        xdr.xdrEncodeString(nonsense);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fixedbuffer = xdr.xdrDecodeByteFixedVector(512);
        buffer = xdr.xdrDecodeByteVector();
        fixedbytes = xdr.xdrDecodeOpaque(demo.FIXEDBUFFERLENGTH);
        bytes = xdr.xdrDecodeDynamicOpaque();
        ui1 = xdr.xdrDecodeInt();
        ui2 = xdr.xdrDecodeInt();
        nonsense = xdr.xdrDecodeString();
    }

}
// End of SILLYSTRUCT.java
