/*
 * Automatically generated by jrpcgen 1.0.7 on 29.05.07 21:34
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SOMERESULT implements XdrAble, java.io.Serializable {
    protected int error;
    protected String typedesc;
    protected byte [] data;

    private static final long serialVersionUID = -6867149493429413131L;

    public void setError(int x) { this.error = x; }
    public int getError() { return this.error; }

    public void setTypedesc(String x) { this.typedesc = x; }
    public String getTypedesc() { return this.typedesc; }

    public void setData(byte[] x) { this.data = x; }
    public void setData(int index, byte x) { this.data[index] = x; }
    public byte[] getData() { return this.data; }
    public byte getData(int index) { return this.data[index]; }

    public SOMERESULT() {
    }

    public SOMERESULT(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(error);
        xdr.xdrEncodeString(typedesc);
        xdr.xdrEncodeDynamicOpaque(data);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        error = xdr.xdrDecodeInt();
        typedesc = xdr.xdrDecodeString();
        data = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of SOMERESULT.java
