/*
 * Automatically generated by jrpcgen 1.0.7 on 29.05.07 21:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SOMERESULT implements XdrAble, java.io.Serializable {
    public int error;
    public String typedesc = ""; 
    public byte [] data;

    private static final long serialVersionUID = -6867149493429413131L;

    public SOMERESULT() {
    }

    public SOMERESULT(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(error);
        xdr.xdrEncodeString(typedesc);
        xdr.xdrEncodeDynamicOpaque(data);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        error = xdr.xdrDecodeInt();
        typedesc = xdr.xdrDecodeString();
        data = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of SOMERESULT.java
