/*
 * Automatically generated by jrpcgen 1.0.7 on 29.05.07 21:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class UNION implements XdrAble, java.io.Serializable {
    public boolean okay;
    public LINKEDLIST list;

    private static final long serialVersionUID = -5038378683068054714L;

    public UNION() {
    }

    public UNION(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeBoolean(okay);
        if ( okay == true ) {
            if ( list != null ) { xdr.xdrEncodeBoolean(true); list.xdrEncode(xdr); } else { xdr.xdrEncodeBoolean(false); };
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        okay = xdr.xdrDecodeBoolean();
        if ( okay == true ) {
            list = xdr.xdrDecodeBoolean() ? new LINKEDLIST(xdr) : null;
        }
    }

}
// End of UNION.java
